"""create_date default added

Revision ID: 3c23bc26d45f
Revises: 70f5827e085f
Create Date: 2025-03-20 11:13:45.021348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c23bc26d45f'
down_revision = '70f5827e085f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
